---
- name: Test connection and run command
  hosts: localhost
  vars_files:
  gather_facts: true
  vars_files:
      - /var/password.yml
  tasks:
    - name: Run command on remote host
      ansible.builtin.command: "sshpass -p '{{ lookup('env', 'SSH_PASSWORD') }}' ssh -o StrictHostKeyChecking=no qaiser@192.168.186.128 'cat /etc/os-release'"
      register: os_release
      delegate_to: localhost
    - name: Run command
      command: cat /etc/os-release
      register: os_release
    - name: Print OS details
      debug:
        var: os_release.stdout_lines
