---
- name: Test connection and run command
  hosts: localhost
  gather_facts: true
  vars_files:
      - /var/password.yml
      
  tasks:
    - name: Run command
      command: cat /etc/os-release
      register: os_release
      
    - name: Print OS details
      debug:
        var: os_release.stdout_lines
        
    - name: Decrypt encrypted file
      command: ansible-vault decrypt /var/checkfile.txt --output /var/decrypted_file.txt --vault-password-file /var/password.yml
      register: decrypt_output

    - name: Print decrypted file contents
      command: cat /var/decrypted_file.txt
      register: decrypted_file_output

    - name: Debug decrypted file contents
      debug:
        var: decrypted_file_output.stdout_lines
