---
- name: SSH Connection
  hosts: myhosts
  gather_facts: false
  vars_files:
    - /var/password.yml
  tasks:
    - name: Establish SSH Connection
      ansible.builtin.ping:
      register: ssh_result

    - name: Print SSH Connection Result
      ansible.builtin.debug:
        var: ssh_result
