---
- name: Test connection and run command
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Run command
      ansible.builtin.command:
        cmd: ssh qaiser@192.168.186.128 'cat /etc/os-release'
      register: os_release

    - name: Print OS details
      debug:
        var: os_release.stdout_lines
