---
- name: Test connection and run command
  hosts: 192.168.186.128
  gather_facts: true
  vars_files:
    - /var/password.yml
    
  tasks:
    - name: Run command
      command: cat /etc/os-release
      register: os_release

    - name: Print OS details
      debug:
        var: os_release.stdout_lines

    - name: Display IP address
      command: "hostname -I"
      register: ip_address_output

    - name: Print IP address
      debug:
        var: ip_address_output.stdout_lines
