---
- name: Test connection and run command
  hosts: qaiser@192.168.186.128
  gather_facts: true
  vars_files:
    - /var/password.yml
    
  tasks:
    - name: Run command
      command: cat /etc/os-release
      register: os_release

    - name: Print OS details
      debug:
        var: os_release.stdout_lines
