---
- name: Test connection and run command
  hosts: localhost
  gather_facts: true
  vars_files:
      - /var/password.yml
      
  tasks:
    - name: Run command
      command: cat /etc/os-release
      register: os_release
      
    - name: Print OS details
      debug:
        var: os_release.stdout_lines
        
    - name: View encrypted file
      command: ansible-vault view /var/checkfile.txt --ask-vault-pass
      register: encrypted_file_output

    - name: Print encrypted file contents
      debug:
        var: encrypted_file_output.stdout_lines
        
    - name: Read hosts file
      slurp:
        src: /var/hosts
      register: hosts_file_content

    - name: Set target host variables
      set_fact:
        target_host: "{{ hosts_file_content['content'] | b64decode | from_yaml }}"

    - name: SSH to target host
      gather_facts: false
      tasks:
        - name: Run command on remote host
          command: echo "Hello, World!"
          register: command_output
          become: yes
          become_user: qaiser
          delegate_to: "{{ target_host['ansible_host'] }}"

        - name: Print command output
          debug:
            var: command_output.stdout_lines
