---
- name: Test connection and run command
  hosts: localhost
  gather_facts: true
  vars_files:
      - /var/password.yml
      
  tasks:
    - name: Run command
      command: cat /etc/os-release
      register: os_release
      
    - name: Print OS details
      debug:
        var: os_release.stdout_lines
        
    - name: View encrypted file
      command: ansible-vault view /var/checkfile.txt --ask-vault-pass
      register: encrypted_file_output

    - name: Print encrypted file contents
      debug:
        var: encrypted_file_output.stdout_lines
        
    - name: Read hosts file
      slurp:
        src: /var/hosts
      register: hosts_file_content

    - name: Set target host variables
      set_fact:
        target_host: "{{ hosts_file_content['content'] | b64decode | from_yaml | first }}"

    - name: Test SSH connection
      wait_for:
        host: "{{ target_host['ansible_host'] }}"
        port: 22
        state: started
        timeout: 10
      register: ssh_connection_status

    - name: Print SSH connection status
      debug:
        msg: "SSH connection to {{ target_host['ansible_host'] }} {{ 'is established' if ssh_connection_status is succeeded else 'failed' }}"
