---
- name: Test connection and run command
  hosts: 192.168.186.128
  gather_facts: true
  become_user: root
  vars_files:
    - var/password.yml
    - var/sudo_password.yml

  tasks:
    - name: Test ping
      ping:

    - name: Run command
      command: cat /etc/os-release
      register: os_release

    - name: Print OS details
      debug:
        var: os_release.stdout_lines

    - name: Display IP address
      command: "hostname -I"
      register: ip_address_output

    - name: Print IP address
      debug:
        var: ip_address_output.stdout_lines

    - name: Set sudo password
      set_fact:
        ansible_become_password: "{{ Sayedali@732 }}"

    - name: Check current user
      command: whoami
      register: current_user

    - name: Print current user
      debug:
        var: current_user.stdout

